### ISSUE TITLE
`resetUser()` exists for Android, not for iOS (nor in TS definitions)

### ISSUE THREAD

**Issue by sneko** [viveapp/capacitor-plugin-freshchat#3]
Hi @EKashpersky ,

I see you implemented for Android the `resetUser()`:
https://github.com/viveapp/capacitor-plugin-freshchat/blob/8135899545c4b6ff6e722fd35d806ae2586e3bed/android/src/main/java/com/freshchat/capacitor/FreshchatCapacitorPlugin.kt#L96-L100

But I don't see it in the TypeScript definition nor in the iOS code. Is it something you finished since then?

(I know the plugin is quite new, just curious)

Thank you,

**Comment by EKashpersky** [comment]
@sneko right, Android platform has more methods implemented, because it was easy.
iOS on the other hand, turned out to be more problematic, so we stick with the methods our app requires.

At the moment all iOS blockers are fixed, but as far as I'm aware we don't plan any extension.

**Comment by sneko** [comment]
@EKashpersky but how do you use those extra-methods implemented since there is no bridge for them in the JavaScript code?

**Comment by EKashpersky** [comment]
@sneko we don't. As I said, during development of iOS part of the plugin, we decided to stick with the methods our app **requires**.

All of them are documented in README.md.

**Comment by sneko** [comment]
@EKashpersky please see https://github.com/viveapp/capacitor-plugin-freshchat/pull/4 that fixes this issue
